name: CI
on: [pull_request]
jobs:
    run-ci-tests:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v3
          - name: set up Python 3.9
            uses: actions/setup-python@v3
            with:
              python-version: "3.9"
          - name: install dependencies
            run: |
              python -m pip install --upgrade pip
              if [-f requirements.txt ]; then pip install -r requirements.txt; fi
          - name: run tests
            run: |
              pytest tests
