name: CI
on: [pull_request]
jobs:
    run-ci-tests:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v3
          - name: run tests
            run: make pytest
